### ISSUE TITLE
Better file-like objects

### ISSUE THREAD

**Issue by geowurster** [geowurster/NewlineJSON#59]
Looking at Python's `io` module I think `NewlineJSON` can use some of its objects and be better at inheritance.

**Comment by eugene-eeo** [comment]
Here's my opinion after spending some time with the library:

 - The current way of doing things is IMHO too complicated. We are pretending to be file objects but we don't have to be! Streaming JSON, in it's very core is just that- a stream. In Python we just give it a different name- generator.
 - The way I'd implement it is just having a very thin layer over file objects:

```python
def read_stream(f):
    for line in f:
        yield json.loads(line)

def get_emitter(f, sep='\n'):
    def emitter(obj):
        f.write(json.dumps(obj) + sep))
    return emitter
```

 - Usage:
```python
emit = get_emitter(open('file', 'w'))
emit({"key": "value"})
emit({"key": "value"})
list(read_stream(open('file', 'r'))) == [{"key": "value"}] * 2
```
 - Since we need to have an option to store the errors I'd also imagine that you want to write a simple class to store the state as well. An alternative, though it tends to get less used in Python is to have an error callback. Just call the supplied function every time we get an error.
 - You can also write a convenience function over the `read_stream` primitive:

```python
def consume(f, **options):
    if isinstance(f, str):
        f = open(stream, mode='r')
    return read_stream(f, **options)
```

**Comment by geowurster** [comment]
@eugene-eeo Yes, the current implementation is absolutely more complicated than it needs to be, but the two functions you mention above are already implemented as `newlinejson.load()` and `newlinejson.dump()`, although they are also overly complicated.  Neither are mentioned in the readme though.

I intend to remove these features:

* Using `'-'` for `stdin/stdout`.
* Skipping lines that do not properly decode.
* Passing file-like objects to `newlinejson.open()`.
* `newlinejson.dumps()` and `newlinejson.loads()` - the input for these functions is pretty ambiguous, so until someone has a real use case they will be flagged as deprecated.

Your point about the file-like objects is correct; everything in this library can be replaced with the two functions you describe above or `newlinejson.load()` and `newlinejson.dump()` if the user is responsible for constructing their own files.  Decoding JSON is particularly easy: `map(json.loads, iterable)`.  This library was initially developed to support a data translation library that transacted in dictionaries internally and serialized to disk as MsgPack, newline JSON, and CSV.  The file-like interface is well defined, familiar to developers, and an expected interface for a lot of tools involving I/O so I see no reason to remove it.  Additionally a package consisting of only `load()` and `dump()` is not worth the maintenance effort.

Currently this library supports a data processing pipeline at my job where any given phase of the pipeline touches tens of millions of newline JSON messages.  All the tasks are engineered to stream data, so having direct access to `f.write()` is important and allows messages to split off from the stream as needed and dropped into different locations based on filtering criteria.  This is where the file-like interface works very well, and the exact pain point this library intends to solve.

I'm thinking something more along the lines of these rough objects.  Note the `load()` and `dump()` that are roughly the same as the functions you outlined above and are much better than their current implementations.

```python
def load(iterable, json_lib=json, **kwargs):
    return _compat.map(functools.partial(json_lib.loads, **kwargs), iterable)


def dump(iterable, fp, json_lib=json, newline=os.linesep, **kwargs):
    write = fp.write
    dumps = json_lib.dumps
    for obj in iterable:
        write(dumps(obj, **kwargs) + newline)


def open(path, mode='r', json_lib=json, newline=os.linesep, **kwargs):
    if '+' in mode:
        raise ValueError("Updating not supported.")

    f = io.FileIO(path, mode=mode)

    if 'r' in mode:
        return NLJTextReader(f, json_lib=json_lib)
    elif 'w' in mode:
        return NLJTextWriter(f, json_lib=json_lib)
    else:
        raise ValueError("Invalid mode: {}".format(mode))


class BaseNLJFile(object):

    def __init__(self, json_lib=json):
        self._json_lib = json_lib

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()


class NLJReader(BaseNLJFile):
    """Base object for readers."""


class NLJWriter(BaseNLJFile):
    """Base object for writers."""

    def __init__(self, newline=os.linesep, **kwargs):
        BaseNLJFile.__init__(self, **kwargs)
        self._newline = newline


class NLJTextReader(base.NLJReader, io.TextIOWrapper):

    def __init__(self, *args, json_lib=json, **kwargs):
        io.TextIOWrapper.__init__(self, *args, **kwargs)
        base.NLJReader.__init__(self, json_lib=json_lib)

    def __next__(self):
        line = io.TextIOWrapper.__next__(self)
        return self._json_lib.loads(line)

    def next(self):
        line = io.TextIOWrapper.next(self)
        return self._json_lib.loads(line)


class NLJTextWriter(base.NLJWriter, io.TextIOWrapper):

    def __init__(self, *args, json_lib=json, newline=os.linesep, **kwargs):
        io.TextIOWrapper.__init__(self, *args, **kwargs)
        base.NLJWriter.__init__(self, json_lib=json_lib, newline=newline)

    def write(self, obj, **kwargs):
        serialized = self._json_lib.dumps(obj, **kwargs)
        return io.TextIOWrapper.write(self, serialized + self._newline)

    def writelines(self, objs, **kwargs):
        for o in objs:
            self.write(o, **kwargs)
```

**Comment by geowurster** [comment]
I'm archiving this repo and closing all open tickets and pull requests.
